Logo = """                                                                                                                                                                                                                                                  
                                                                                                                                                                dddddddd                                                                          
MMMMMMMM               MMMMMMMM                                                                                       CCCCCCCCCCCCC                             d::::::d                              ((((((                           ))))))     
M:::::::M             M:::::::M                                                                                    CCC::::::::::::C                             d::::::d                            ((::::::(                         )::::::))   
M::::::::M           M::::::::M                                                                                  CC:::::::::::::::C                             d::::::d                          ((:::::::(                           ):::::::)) 
M:::::::::M         M:::::::::M                                                                                 C:::::CCCCCCCC::::C                             d:::::d                          (:::::::((                             )):::::::)
M::::::::::M       M::::::::::M   ooooooooooo   rrrrr   rrrrrrrrr       ssssssssss       eeeeeeeeeeee          C:::::C       CCCCCC   ooooooooooo       ddddddddd:::::d     eeeeeeeeeeee         (::::::(                                 )::::::)
M:::::::::::M     M:::::::::::M oo:::::::::::oo r::::rrr:::::::::r    ss::::::::::s    ee::::::::::::ee       C:::::C               oo:::::::::::oo   dd::::::::::::::d   ee::::::::::::ee       (:::::(                                   ):::::)
M:::::::M::::M   M::::M:::::::Mo:::::::::::::::or:::::::::::::::::r ss:::::::::::::s  e::::::eeeee:::::ee     C:::::C              o:::::::::::::::o d::::::::::::::::d  e::::::eeeee:::::ee     (:::::(                                   ):::::)
M::::::M M::::M M::::M M::::::Mo:::::ooooo:::::orr::::::rrrrr::::::rs::::::ssss:::::se::::::e     e:::::e     C:::::C              o:::::ooooo:::::od:::::::ddddd:::::d e::::::e     e:::::e     (:::::(              ---------------      ):::::)
M::::::M  M::::M::::M  M::::::Mo::::o     o::::o r:::::r     r:::::r s:::::s  ssssss e:::::::eeeee::::::e     C:::::C              o::::o     o::::od::::::d    d:::::d e:::::::eeeee::::::e     (:::::(              -:::::::::::::-      ):::::)
M::::::M   M:::::::M   M::::::Mo::::o     o::::o r:::::r     rrrrrrr   s::::::s      e:::::::::::::::::e      C:::::C              o::::o     o::::od:::::d     d:::::d e:::::::::::::::::e      (:::::(              ---------------      ):::::)
M::::::M    M:::::M    M::::::Mo::::o     o::::o r:::::r                  s::::::s   e::::::eeeeeeeeeee       C:::::C              o::::o     o::::od:::::d     d:::::d e::::::eeeeeeeeeee       (:::::(                                   ):::::)
M::::::M     MMMMM     M::::::Mo::::o     o::::o r:::::r            ssssss   s:::::s e:::::::e                 C:::::C       CCCCCCo::::o     o::::od:::::d     d:::::d e:::::::e                (::::::(                                 )::::::)
M::::::M               M::::::Mo:::::ooooo:::::o r:::::r            s:::::ssss::::::se::::::::e                 C:::::CCCCCCCC::::Co:::::ooooo:::::od::::::ddddd::::::dde::::::::e               (:::::::((                             )):::::::)
M::::::M               M::::::Mo:::::::::::::::o r:::::r            s::::::::::::::s  e::::::::eeeeeeee          CC:::::::::::::::Co:::::::::::::::o d:::::::::::::::::d e::::::::eeeeeeee        ((:::::::(  ......                   ):::::::)) 
M::::::M               M::::::M oo:::::::::::oo  r:::::r             s:::::::::::ss    ee:::::::::::::e            CCC::::::::::::C oo:::::::::::oo   d:::::::::ddd::::d  ee:::::::::::::e          ((::::::( .::::.                  )::::::)    
MMMMMMMM               MMMMMMMM   ooooooooooo    rrrrrrr              sssssssssss        eeeeeeeeeeeeee               CCCCCCCCCCCCC   ooooooooooo      ddddddddd   ddddd    eeeeeeeeeeeeee            ((((((  ......                   ))))))     
                                            
 """